version: '2'
services:
    hisampleapplication-app:
        image: hisampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://hisampleapplication-mariadb:3306/hisampleapplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8086:8086
    hisampleapplication-mariadb:
        extends:
            file: mariadb.yml
            service: hisampleapplication-mariadb
